#include <iostream>
using namespace std;
int main()
{
	int n;
	cout <<"ingrese el numero del 1 al 7 "<<endl;
 	cin>>n;
 	
 	
 	switch (n)
 	{
 			case 1: 
 			cout<<"lunes ";
 			break;
 			case 2:
 			cout<<"martes";
 			break;
 			case 3: 
 			cout<<"miercoles ";
 			break;
 			case 4: 
 			cout<<"jueves";
 			break;
 			case 5: 
 			cout<<"viernes ";
 			break;
 			case 6:
 			cout<<"sabado ";
 			break;
 			case 7:
 			cout<<"domingo ";
 			break;
 			
 			
 			
 			default:
 			cout<<"opcion no valida";
 				
	 }
 	return 0;
 	
 	
 	
 	
 	
}
